name: ci

on:
  pull_request_target:
    types: [labeled]

  pull_request: ~

  push:

  workflow_dispatch:

jobs:
  ci:
    if: ${{ !github.event.pull_request.head.repo.fork || github.event.label.name == 'ci-approved' || !contains(fromJSON('["pull_request", "pull_request_target"]'), github.event_name) }}
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "${{ github.event_name }}"
          echo "${{ github.event.pull_request.head.sha }}"
          echo "${{ github.event.pull_request.head.repo.fork }}"
          echo "${{ github.event.label.name }}"
          echo "${{ toJSON(github) }}"

      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - run: cat test
