name: ci

on:
  pull_request_target:
    types: [labeled]

  pull_request: ~

  push:
    branches:
      - 'main'
    tags-ignore:
      - '**'

  workflow_dispatch: ~

jobs:
  ci:
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.head.repo.fork && github.event.action != 'labeled' || github.event.label.name == 'ci-approved' }}
    steps:
      - name: run CI
        run: echo "CI"
