name: ci

on:
  pull_request_target:
    types: [labeled]

jobs:
  ci:
    if: ${{ github.event.label.name == 'ci-approved' }}
    runs-on: ubuntu-latest

    steps:
      - name: 1 minute delay
        run: sleep 60

      - run: echo "${{ github.event.pull_request.head.sha }}"
