name: ci

on:
  pull_request_target:
    types: [labeled]

  pull_request: ~

  push:
    branches:
      - 'main'
    tags-ignore:
      - '**'

  workflow_dispatch: ~

jobs:
  pr-label:
    if: ${{ !github.event.pull_request.head.repo.fork || github.event.label.name == 'ci-approved'}}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - run: |
          echo "${{ github.event_name }}"
          echo "${{ github.event.pull_request.head.sha }}"
          echo "${{ github.event.pull_request.head.repo.fork }}"
          echo "${{ github.event.label.name }}"
          echo "${{ toJSON(github) }}"

      - name: Remove PR label
        if: ${{ github.event_name == 'pull_request_target' }}
        run: |
          curl -w "%{http_code}\\n" -L \
          -X DELETE \
          -H "Authorization: token ${{ secrets.REPO_TOKEN }}" \
          --url https://api.github.com/repos/ecmwf-enterprise-sandbox/pull-request-ci/issues/${{ github.event.number }}/labels/ci-approved

  ci:
    runs-on: ubuntu-latest
    needs: [pr-label] # if labeler is skipped => triggered by unapproved public PR => this job is skipped as well
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - run: cat test
