name: ci

on:
  pull_request_target:
    types: [labeled]

  pull_request: ~

jobs:
  ci:
    if: ${{ !github.event.pull_request.head.fork || github.event.label.name == 'ci-approved' }}
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "${{ github.event_name }}"
          echo "${{ github.event.pull_request.head.sha }}"
          echo "${{ github.event.pull_request.head.fork }}"
          echo "${{ github.event.label.name }}"

      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - run: cat test
