# Manage labels of pull requests that originate from forks
name: label-public-pr

on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  label:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.head.repo.fork }}
    steps:
      - name: Add label `contributor`
        if: ${{ github.event.action == 'opened' }}
        uses: ecmwf-actions/labeler@v1
        with:
          issue: ${{ github.event.number }}
          label: contributor
          action: add

      - name: Remove label `approved-for-ci`
        if: ${{ github.event.action == 'synchronize' }}
        uses: ecmwf-actions/labeler@v1
        with:
          issue: ${{ github.event.number }}
          label: approved-for-ci
          action: remove
